// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenseClient.proto

package ai.cochlear.sense.proto;

public final class SenseClient {
  private SenseClient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AudioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sense.full.v1.Audio)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int64 segmentOffset = 2;</code>
     * @return The segmentOffset.
     */
    long getSegmentOffset();

    /**
     * <code>double segmentStartTime = 3;</code>
     * @return The segmentStartTime.
     */
    double getSegmentStartTime();
  }
  /**
   * Protobuf type {@code sense.full.v1.Audio}
   */
  public  static final class Audio extends
      com.google.protobuf.GeneratedMessageLite<
          Audio, Audio.Builder> implements
      // @@protoc_insertion_point(message_implements:sense.full.v1.Audio)
      AudioOrBuilder {
    private Audio() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 1;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 1;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static final int SEGMENTOFFSET_FIELD_NUMBER = 2;
    private long segmentOffset_;
    /**
     * <code>int64 segmentOffset = 2;</code>
     * @return The segmentOffset.
     */
    @java.lang.Override
    public long getSegmentOffset() {
      return segmentOffset_;
    }
    /**
     * <code>int64 segmentOffset = 2;</code>
     * @param value The segmentOffset to set.
     */
    private void setSegmentOffset(long value) {
      
      segmentOffset_ = value;
    }
    /**
     * <code>int64 segmentOffset = 2;</code>
     */
    private void clearSegmentOffset() {
      
      segmentOffset_ = 0L;
    }

    public static final int SEGMENTSTARTTIME_FIELD_NUMBER = 3;
    private double segmentStartTime_;
    /**
     * <code>double segmentStartTime = 3;</code>
     * @return The segmentStartTime.
     */
    @java.lang.Override
    public double getSegmentStartTime() {
      return segmentStartTime_;
    }
    /**
     * <code>double segmentStartTime = 3;</code>
     * @param value The segmentStartTime to set.
     */
    private void setSegmentStartTime(double value) {
      
      segmentStartTime_ = value;
    }
    /**
     * <code>double segmentStartTime = 3;</code>
     */
    private void clearSegmentStartTime() {
      
      segmentStartTime_ = 0D;
    }

    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.Audio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ai.cochlear.sense.proto.SenseClient.Audio prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code sense.full.v1.Audio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ai.cochlear.sense.proto.SenseClient.Audio, Builder> implements
        // @@protoc_insertion_point(builder_implements:sense.full.v1.Audio)
        ai.cochlear.sense.proto.SenseClient.AudioOrBuilder {
      // Construct using ai.cochlear.sense.proto.SenseClient.Audio.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <code>int64 segmentOffset = 2;</code>
       * @return The segmentOffset.
       */
      @java.lang.Override
      public long getSegmentOffset() {
        return instance.getSegmentOffset();
      }
      /**
       * <code>int64 segmentOffset = 2;</code>
       * @param value The segmentOffset to set.
       * @return This builder for chaining.
       */
      public Builder setSegmentOffset(long value) {
        copyOnWrite();
        instance.setSegmentOffset(value);
        return this;
      }
      /**
       * <code>int64 segmentOffset = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSegmentOffset() {
        copyOnWrite();
        instance.clearSegmentOffset();
        return this;
      }

      /**
       * <code>double segmentStartTime = 3;</code>
       * @return The segmentStartTime.
       */
      @java.lang.Override
      public double getSegmentStartTime() {
        return instance.getSegmentStartTime();
      }
      /**
       * <code>double segmentStartTime = 3;</code>
       * @param value The segmentStartTime to set.
       * @return This builder for chaining.
       */
      public Builder setSegmentStartTime(double value) {
        copyOnWrite();
        instance.setSegmentStartTime(value);
        return this;
      }
      /**
       * <code>double segmentStartTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSegmentStartTime() {
        copyOnWrite();
        instance.clearSegmentStartTime();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sense.full.v1.Audio)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ai.cochlear.sense.proto.SenseClient.Audio();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "data_",
              "segmentOffset_",
              "segmentStartTime_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\n\u0002\u0002" +
                "\u0003\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ai.cochlear.sense.proto.SenseClient.Audio> parser = PARSER;
          if (parser == null) {
            synchronized (ai.cochlear.sense.proto.SenseClient.Audio.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ai.cochlear.sense.proto.SenseClient.Audio>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:sense.full.v1.Audio)
    private static final ai.cochlear.sense.proto.SenseClient.Audio DEFAULT_INSTANCE;
    static {
      Audio defaultInstance = new Audio();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Audio.class, defaultInstance);
    }

    public static ai.cochlear.sense.proto.SenseClient.Audio getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Audio> PARSER;

    public static com.google.protobuf.Parser<Audio> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sense.full.v1.Event)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string tag = 1;</code>
     * @return The tag.
     */
    java.lang.String getTag();
    /**
     * <code>string tag = 1;</code>
     * @return The bytes for tag.
     */
    com.google.protobuf.ByteString
        getTagBytes();

    /**
     * <code>double startTime = 2;</code>
     * @return The startTime.
     */
    double getStartTime();

    /**
     * <code>double endTime = 3;</code>
     * @return The endTime.
     */
    double getEndTime();

    /**
     * <code>double probability = 4;</code>
     * @return The probability.
     */
    double getProbability();
  }
  /**
   * Protobuf type {@code sense.full.v1.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageLite<
          Event, Event.Builder> implements
      // @@protoc_insertion_point(message_implements:sense.full.v1.Event)
      EventOrBuilder {
    private Event() {
      tag_ = "";
    }
    public static final int TAG_FIELD_NUMBER = 1;
    private java.lang.String tag_;
    /**
     * <code>string tag = 1;</code>
     * @return The tag.
     */
    @java.lang.Override
    public java.lang.String getTag() {
      return tag_;
    }
    /**
     * <code>string tag = 1;</code>
     * @return The bytes for tag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(tag_);
    }
    /**
     * <code>string tag = 1;</code>
     * @param value The tag to set.
     */
    private void setTag(
        java.lang.String value) {
      value.getClass();
  
      tag_ = value;
    }
    /**
     * <code>string tag = 1;</code>
     */
    private void clearTag() {
      
      tag_ = getDefaultInstance().getTag();
    }
    /**
     * <code>string tag = 1;</code>
     * @param value The bytes for tag to set.
     */
    private void setTagBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      tag_ = value.toStringUtf8();
      
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private double startTime_;
    /**
     * <code>double startTime = 2;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public double getStartTime() {
      return startTime_;
    }
    /**
     * <code>double startTime = 2;</code>
     * @param value The startTime to set.
     */
    private void setStartTime(double value) {
      
      startTime_ = value;
    }
    /**
     * <code>double startTime = 2;</code>
     */
    private void clearStartTime() {
      
      startTime_ = 0D;
    }

    public static final int ENDTIME_FIELD_NUMBER = 3;
    private double endTime_;
    /**
     * <code>double endTime = 3;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public double getEndTime() {
      return endTime_;
    }
    /**
     * <code>double endTime = 3;</code>
     * @param value The endTime to set.
     */
    private void setEndTime(double value) {
      
      endTime_ = value;
    }
    /**
     * <code>double endTime = 3;</code>
     */
    private void clearEndTime() {
      
      endTime_ = 0D;
    }

    public static final int PROBABILITY_FIELD_NUMBER = 4;
    private double probability_;
    /**
     * <code>double probability = 4;</code>
     * @return The probability.
     */
    @java.lang.Override
    public double getProbability() {
      return probability_;
    }
    /**
     * <code>double probability = 4;</code>
     * @param value The probability to set.
     */
    private void setProbability(double value) {
      
      probability_ = value;
    }
    /**
     * <code>double probability = 4;</code>
     */
    private void clearProbability() {
      
      probability_ = 0D;
    }

    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ai.cochlear.sense.proto.SenseClient.Event prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code sense.full.v1.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ai.cochlear.sense.proto.SenseClient.Event, Builder> implements
        // @@protoc_insertion_point(builder_implements:sense.full.v1.Event)
        ai.cochlear.sense.proto.SenseClient.EventOrBuilder {
      // Construct using ai.cochlear.sense.proto.SenseClient.Event.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string tag = 1;</code>
       * @return The tag.
       */
      @java.lang.Override
      public java.lang.String getTag() {
        return instance.getTag();
      }
      /**
       * <code>string tag = 1;</code>
       * @return The bytes for tag.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTagBytes() {
        return instance.getTagBytes();
      }
      /**
       * <code>string tag = 1;</code>
       * @param value The tag to set.
       * @return This builder for chaining.
       */
      public Builder setTag(
          java.lang.String value) {
        copyOnWrite();
        instance.setTag(value);
        return this;
      }
      /**
       * <code>string tag = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTag() {
        copyOnWrite();
        instance.clearTag();
        return this;
      }
      /**
       * <code>string tag = 1;</code>
       * @param value The bytes for tag to set.
       * @return This builder for chaining.
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTagBytes(value);
        return this;
      }

      /**
       * <code>double startTime = 2;</code>
       * @return The startTime.
       */
      @java.lang.Override
      public double getStartTime() {
        return instance.getStartTime();
      }
      /**
       * <code>double startTime = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(double value) {
        copyOnWrite();
        instance.setStartTime(value);
        return this;
      }
      /**
       * <code>double startTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        copyOnWrite();
        instance.clearStartTime();
        return this;
      }

      /**
       * <code>double endTime = 3;</code>
       * @return The endTime.
       */
      @java.lang.Override
      public double getEndTime() {
        return instance.getEndTime();
      }
      /**
       * <code>double endTime = 3;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(double value) {
        copyOnWrite();
        instance.setEndTime(value);
        return this;
      }
      /**
       * <code>double endTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        copyOnWrite();
        instance.clearEndTime();
        return this;
      }

      /**
       * <code>double probability = 4;</code>
       * @return The probability.
       */
      @java.lang.Override
      public double getProbability() {
        return instance.getProbability();
      }
      /**
       * <code>double probability = 4;</code>
       * @param value The probability to set.
       * @return This builder for chaining.
       */
      public Builder setProbability(double value) {
        copyOnWrite();
        instance.setProbability(value);
        return this;
      }
      /**
       * <code>double probability = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProbability() {
        copyOnWrite();
        instance.clearProbability();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sense.full.v1.Event)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ai.cochlear.sense.proto.SenseClient.Event();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "tag_",
              "startTime_",
              "endTime_",
              "probability_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0000" +
                "\u0003\u0000\u0004\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ai.cochlear.sense.proto.SenseClient.Event> parser = PARSER;
          if (parser == null) {
            synchronized (ai.cochlear.sense.proto.SenseClient.Event.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ai.cochlear.sense.proto.SenseClient.Event>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:sense.full.v1.Event)
    private static final ai.cochlear.sense.proto.SenseClient.Event DEFAULT_INSTANCE;
    static {
      Event defaultInstance = new Event();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Event.class, defaultInstance);
    }

    public static ai.cochlear.sense.proto.SenseClient.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Event> PARSER;

    public static com.google.protobuf.Parser<Event> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CochlSenseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sense.full.v1.CochlSense)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string service = 1;</code>
     * @return The service.
     */
    java.lang.String getService();
    /**
     * <code>string service = 1;</code>
     * @return The bytes for service.
     */
    com.google.protobuf.ByteString
        getServiceBytes();

    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    java.util.List<ai.cochlear.sense.proto.SenseClient.Event> 
        getEventsList();
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    ai.cochlear.sense.proto.SenseClient.Event getEvents(int index);
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    int getEventsCount();
  }
  /**
   * Protobuf type {@code sense.full.v1.CochlSense}
   */
  public  static final class CochlSense extends
      com.google.protobuf.GeneratedMessageLite<
          CochlSense, CochlSense.Builder> implements
      // @@protoc_insertion_point(message_implements:sense.full.v1.CochlSense)
      CochlSenseOrBuilder {
    private CochlSense() {
      service_ = "";
      events_ = emptyProtobufList();
    }
    public static final int SERVICE_FIELD_NUMBER = 1;
    private java.lang.String service_;
    /**
     * <code>string service = 1;</code>
     * @return The service.
     */
    @java.lang.Override
    public java.lang.String getService() {
      return service_;
    }
    /**
     * <code>string service = 1;</code>
     * @return The bytes for service.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getServiceBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(service_);
    }
    /**
     * <code>string service = 1;</code>
     * @param value The service to set.
     */
    private void setService(
        java.lang.String value) {
      value.getClass();
  
      service_ = value;
    }
    /**
     * <code>string service = 1;</code>
     */
    private void clearService() {
      
      service_ = getDefaultInstance().getService();
    }
    /**
     * <code>string service = 1;</code>
     * @param value The bytes for service to set.
     */
    private void setServiceBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      service_ = value.toStringUtf8();
      
    }

    public static final int EVENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<ai.cochlear.sense.proto.SenseClient.Event> events_;
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    @java.lang.Override
    public java.util.List<ai.cochlear.sense.proto.SenseClient.Event> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    public java.util.List<? extends ai.cochlear.sense.proto.SenseClient.EventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    @java.lang.Override
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    @java.lang.Override
    public ai.cochlear.sense.proto.SenseClient.Event getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    public ai.cochlear.sense.proto.SenseClient.EventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }
    private void ensureEventsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<ai.cochlear.sense.proto.SenseClient.Event> tmp = events_;
      if (!tmp.isModifiable()) {
        events_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    private void setEvents(
        int index, ai.cochlear.sense.proto.SenseClient.Event value) {
      value.getClass();
  ensureEventsIsMutable();
      events_.set(index, value);
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    private void addEvents(ai.cochlear.sense.proto.SenseClient.Event value) {
      value.getClass();
  ensureEventsIsMutable();
      events_.add(value);
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    private void addEvents(
        int index, ai.cochlear.sense.proto.SenseClient.Event value) {
      value.getClass();
  ensureEventsIsMutable();
      events_.add(index, value);
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    private void addAllEvents(
        java.lang.Iterable<? extends ai.cochlear.sense.proto.SenseClient.Event> values) {
      ensureEventsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, events_);
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    private void clearEvents() {
      events_ = emptyProtobufList();
    }
    /**
     * <code>repeated .sense.full.v1.Event events = 2;</code>
     */
    private void removeEvents(int index) {
      ensureEventsIsMutable();
      events_.remove(index);
    }

    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ai.cochlear.sense.proto.SenseClient.CochlSense parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ai.cochlear.sense.proto.SenseClient.CochlSense prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code sense.full.v1.CochlSense}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ai.cochlear.sense.proto.SenseClient.CochlSense, Builder> implements
        // @@protoc_insertion_point(builder_implements:sense.full.v1.CochlSense)
        ai.cochlear.sense.proto.SenseClient.CochlSenseOrBuilder {
      // Construct using ai.cochlear.sense.proto.SenseClient.CochlSense.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string service = 1;</code>
       * @return The service.
       */
      @java.lang.Override
      public java.lang.String getService() {
        return instance.getService();
      }
      /**
       * <code>string service = 1;</code>
       * @return The bytes for service.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getServiceBytes() {
        return instance.getServiceBytes();
      }
      /**
       * <code>string service = 1;</code>
       * @param value The service to set.
       * @return This builder for chaining.
       */
      public Builder setService(
          java.lang.String value) {
        copyOnWrite();
        instance.setService(value);
        return this;
      }
      /**
       * <code>string service = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearService() {
        copyOnWrite();
        instance.clearService();
        return this;
      }
      /**
       * <code>string service = 1;</code>
       * @param value The bytes for service to set.
       * @return This builder for chaining.
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setServiceBytes(value);
        return this;
      }

      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      @java.lang.Override
      public java.util.List<ai.cochlear.sense.proto.SenseClient.Event> getEventsList() {
        return java.util.Collections.unmodifiableList(
            instance.getEventsList());
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      @java.lang.Override
      public int getEventsCount() {
        return instance.getEventsCount();
      }/**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      @java.lang.Override
      public ai.cochlear.sense.proto.SenseClient.Event getEvents(int index) {
        return instance.getEvents(index);
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder setEvents(
          int index, ai.cochlear.sense.proto.SenseClient.Event value) {
        copyOnWrite();
        instance.setEvents(index, value);
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder setEvents(
          int index, ai.cochlear.sense.proto.SenseClient.Event.Builder builderForValue) {
        copyOnWrite();
        instance.setEvents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder addEvents(ai.cochlear.sense.proto.SenseClient.Event value) {
        copyOnWrite();
        instance.addEvents(value);
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder addEvents(
          int index, ai.cochlear.sense.proto.SenseClient.Event value) {
        copyOnWrite();
        instance.addEvents(index, value);
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder addEvents(
          ai.cochlear.sense.proto.SenseClient.Event.Builder builderForValue) {
        copyOnWrite();
        instance.addEvents(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder addEvents(
          int index, ai.cochlear.sense.proto.SenseClient.Event.Builder builderForValue) {
        copyOnWrite();
        instance.addEvents(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends ai.cochlear.sense.proto.SenseClient.Event> values) {
        copyOnWrite();
        instance.addAllEvents(values);
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder clearEvents() {
        copyOnWrite();
        instance.clearEvents();
        return this;
      }
      /**
       * <code>repeated .sense.full.v1.Event events = 2;</code>
       */
      public Builder removeEvents(int index) {
        copyOnWrite();
        instance.removeEvents(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sense.full.v1.CochlSense)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ai.cochlear.sense.proto.SenseClient.CochlSense();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "service_",
              "events_",
              ai.cochlear.sense.proto.SenseClient.Event.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0208\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ai.cochlear.sense.proto.SenseClient.CochlSense> parser = PARSER;
          if (parser == null) {
            synchronized (ai.cochlear.sense.proto.SenseClient.CochlSense.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ai.cochlear.sense.proto.SenseClient.CochlSense>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:sense.full.v1.CochlSense)
    private static final ai.cochlear.sense.proto.SenseClient.CochlSense DEFAULT_INSTANCE;
    static {
      CochlSense defaultInstance = new CochlSense();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CochlSense.class, defaultInstance);
    }

    public static ai.cochlear.sense.proto.SenseClient.CochlSense getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CochlSense> PARSER;

    public static com.google.protobuf.Parser<CochlSense> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
