// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenseClient.proto

package ai.cochlear.sense.grpc;

public interface RequestStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sense.full.v1.RequestStream)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>string apikey = 2;</code>
   * @return The apikey.
   */
  String getApikey();
  /**
   * <code>string apikey = 2;</code>
   * @return The bytes for apikey.
   */
  com.google.protobuf.ByteString
      getApikeyBytes();

  /**
   * <code>string dtype = 3;</code>
   * @return The dtype.
   */
  String getDtype();
  /**
   * <code>string dtype = 3;</code>
   * @return The bytes for dtype.
   */
  com.google.protobuf.ByteString
      getDtypeBytes();

  /**
   * <code>int32 sr = 4;</code>
   * @return The sr.
   */
  int getSr();

  /**
   * <code>string api_version = 5;</code>
   * @return The apiVersion.
   */
  String getApiVersion();
  /**
   * <code>string api_version = 5;</code>
   * @return The bytes for apiVersion.
   */
  com.google.protobuf.ByteString
      getApiVersionBytes();

  /**
   * <code>string user_agent = 6;</code>
   * @return The userAgent.
   */
  String getUserAgent();
  /**
   * <code>string user_agent = 6;</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();
}
