// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenseClient.proto

package ai.cochlear.sense.grpc;

/**
 * Protobuf type {@code sense.full.v1.Response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessageLite<
        Response, Response.Builder> implements
    // @@protoc_insertion_point(message_implements:sense.full.v1.Response)
    ResponseOrBuilder {
  private Response() {
    outputs_ = "";
  }
  public static final int OUTPUTS_FIELD_NUMBER = 1;
  private String outputs_;
  /**
   * <code>string outputs = 1;</code>
   * @return The outputs.
   */
  @Override
  public String getOutputs() {
    return outputs_;
  }
  /**
   * <code>string outputs = 1;</code>
   * @return The bytes for outputs.
   */
  @Override
  public com.google.protobuf.ByteString
      getOutputsBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(outputs_);
  }
  /**
   * <code>string outputs = 1;</code>
   * @param value The outputs to set.
   */
  private void setOutputs(
      String value) {
    value.getClass();

    outputs_ = value;
  }
  /**
   * <code>string outputs = 1;</code>
   */
  private void clearOutputs() {

    outputs_ = getDefaultInstance().getOutputs();
  }
  /**
   * <code>string outputs = 1;</code>
   * @param value The bytes for outputs to set.
   */
  private void setOutputsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    outputs_ = value.toStringUtf8();

  }

  public static Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(Response prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code sense.full.v1.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        Response, Builder> implements
      // @@protoc_insertion_point(builder_implements:sense.full.v1.Response)
      ai.cochlear.sense.grpc.ResponseOrBuilder {
    // Construct using ai.cochlear.sense.grpc.Response.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string outputs = 1;</code>
     * @return The outputs.
     */
    @Override
    public String getOutputs() {
      return instance.getOutputs();
    }
    /**
     * <code>string outputs = 1;</code>
     * @return The bytes for outputs.
     */
    @Override
    public com.google.protobuf.ByteString
        getOutputsBytes() {
      return instance.getOutputsBytes();
    }
    /**
     * <code>string outputs = 1;</code>
     * @param value The outputs to set.
     * @return This builder for chaining.
     */
    public Builder setOutputs(
        String value) {
      copyOnWrite();
      instance.setOutputs(value);
      return this;
    }
    /**
     * <code>string outputs = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputs() {
      copyOnWrite();
      instance.clearOutputs();
      return this;
    }
    /**
     * <code>string outputs = 1;</code>
     * @param value The bytes for outputs to set.
     * @return This builder for chaining.
     */
    public Builder setOutputsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOutputsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sense.full.v1.Response)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new Response();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "outputs_",
          };
          String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<Response> parser = PARSER;
        if (parser == null) {
          synchronized (Response.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<Response>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sense.full.v1.Response)
  private static final Response DEFAULT_INSTANCE;
  static {
    Response defaultInstance = new Response();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Response.class, defaultInstance);
  }

  public static Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Response> PARSER;

  public static com.google.protobuf.Parser<Response> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

