// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenseClient.proto

package ai.cochlear.sense.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sense.full.v1.Response)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string outputs = 1;</code>
   * @return The outputs.
   */
  String getOutputs();
  /**
   * <code>string outputs = 1;</code>
   * @return The bytes for outputs.
   */
  com.google.protobuf.ByteString
      getOutputsBytes();
}
