// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenseClient.proto

package ai.cochlear.sense.grpc;

/**
 * <pre>
 * message input option
 * </pre>
 *
 * Protobuf type {@code sense.full.v1.Request}
 */
public  final class Request extends
    com.google.protobuf.GeneratedMessageLite<
        Request, Request.Builder> implements
    // @@protoc_insertion_point(message_implements:sense.full.v1.Request)
    RequestOrBuilder {
  private Request() {
    data_ = com.google.protobuf.ByteString.EMPTY;
    apikey_ = "";
    format_ = "";
    apiVersion_ = "";
    userAgent_ = "";
  }
  public static final int DATA_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  @Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }
  /**
   * <code>bytes data = 1;</code>
   * @param value The data to set.
   */
  private void setData(com.google.protobuf.ByteString value) {
    value.getClass();

    data_ = value;
  }
  /**
   * <code>bytes data = 1;</code>
   */
  private void clearData() {

    data_ = getDefaultInstance().getData();
  }

  public static final int APIKEY_FIELD_NUMBER = 2;
  private String apikey_;
  /**
   * <code>string apikey = 2;</code>
   * @return The apikey.
   */
  @Override
  public String getApikey() {
    return apikey_;
  }
  /**
   * <code>string apikey = 2;</code>
   * @return The bytes for apikey.
   */
  @Override
  public com.google.protobuf.ByteString
      getApikeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(apikey_);
  }
  /**
   * <code>string apikey = 2;</code>
   * @param value The apikey to set.
   */
  private void setApikey(
      String value) {
    value.getClass();

    apikey_ = value;
  }
  /**
   * <code>string apikey = 2;</code>
   */
  private void clearApikey() {

    apikey_ = getDefaultInstance().getApikey();
  }
  /**
   * <code>string apikey = 2;</code>
   * @param value The bytes for apikey to set.
   */
  private void setApikeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    apikey_ = value.toStringUtf8();

  }

  public static final int FORMAT_FIELD_NUMBER = 3;
  private String format_;
  /**
   * <code>string format = 3;</code>
   * @return The format.
   */
  @Override
  public String getFormat() {
    return format_;
  }
  /**
   * <code>string format = 3;</code>
   * @return The bytes for format.
   */
  @Override
  public com.google.protobuf.ByteString
      getFormatBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(format_);
  }
  /**
   * <code>string format = 3;</code>
   * @param value The format to set.
   */
  private void setFormat(
      String value) {
    value.getClass();

    format_ = value;
  }
  /**
   * <code>string format = 3;</code>
   */
  private void clearFormat() {

    format_ = getDefaultInstance().getFormat();
  }
  /**
   * <code>string format = 3;</code>
   * @param value The bytes for format to set.
   */
  private void setFormatBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    format_ = value.toStringUtf8();

  }

  public static final int API_VERSION_FIELD_NUMBER = 4;
  private String apiVersion_;
  /**
   * <code>string api_version = 4;</code>
   * @return The apiVersion.
   */
  @Override
  public String getApiVersion() {
    return apiVersion_;
  }
  /**
   * <code>string api_version = 4;</code>
   * @return The bytes for apiVersion.
   */
  @Override
  public com.google.protobuf.ByteString
      getApiVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(apiVersion_);
  }
  /**
   * <code>string api_version = 4;</code>
   * @param value The apiVersion to set.
   */
  private void setApiVersion(
      String value) {
    value.getClass();

    apiVersion_ = value;
  }
  /**
   * <code>string api_version = 4;</code>
   */
  private void clearApiVersion() {

    apiVersion_ = getDefaultInstance().getApiVersion();
  }
  /**
   * <code>string api_version = 4;</code>
   * @param value The bytes for apiVersion to set.
   */
  private void setApiVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    apiVersion_ = value.toStringUtf8();

  }

  public static final int USER_AGENT_FIELD_NUMBER = 5;
  private String userAgent_;
  /**
   * <code>string user_agent = 5;</code>
   * @return The userAgent.
   */
  @Override
  public String getUserAgent() {
    return userAgent_;
  }
  /**
   * <code>string user_agent = 5;</code>
   * @return The bytes for userAgent.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserAgentBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userAgent_);
  }
  /**
   * <code>string user_agent = 5;</code>
   * @param value The userAgent to set.
   */
  private void setUserAgent(
      String value) {
    value.getClass();

    userAgent_ = value;
  }
  /**
   * <code>string user_agent = 5;</code>
   */
  private void clearUserAgent() {

    userAgent_ = getDefaultInstance().getUserAgent();
  }
  /**
   * <code>string user_agent = 5;</code>
   * @param value The bytes for userAgent to set.
   */
  private void setUserAgentBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userAgent_ = value.toStringUtf8();

  }

  public static Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(Request prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * message input option
   * </pre>
   *
   * Protobuf type {@code sense.full.v1.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        Request, Builder> implements
      // @@protoc_insertion_point(builder_implements:sense.full.v1.Request)
      RequestOrBuilder {
    // Construct using ai.cochlear.sense.grpc.Request.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return instance.getData();
    }
    /**
     * <code>bytes data = 1;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setData(value);
      return this;
    }
    /**
     * <code>bytes data = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      copyOnWrite();
      instance.clearData();
      return this;
    }

    /**
     * <code>string apikey = 2;</code>
     * @return The apikey.
     */
    @Override
    public String getApikey() {
      return instance.getApikey();
    }
    /**
     * <code>string apikey = 2;</code>
     * @return The bytes for apikey.
     */
    @Override
    public com.google.protobuf.ByteString
        getApikeyBytes() {
      return instance.getApikeyBytes();
    }
    /**
     * <code>string apikey = 2;</code>
     * @param value The apikey to set.
     * @return This builder for chaining.
     */
    public Builder setApikey(
        String value) {
      copyOnWrite();
      instance.setApikey(value);
      return this;
    }
    /**
     * <code>string apikey = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearApikey() {
      copyOnWrite();
      instance.clearApikey();
      return this;
    }
    /**
     * <code>string apikey = 2;</code>
     * @param value The bytes for apikey to set.
     * @return This builder for chaining.
     */
    public Builder setApikeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setApikeyBytes(value);
      return this;
    }

    /**
     * <code>string format = 3;</code>
     * @return The format.
     */
    @Override
    public String getFormat() {
      return instance.getFormat();
    }
    /**
     * <code>string format = 3;</code>
     * @return The bytes for format.
     */
    @Override
    public com.google.protobuf.ByteString
        getFormatBytes() {
      return instance.getFormatBytes();
    }
    /**
     * <code>string format = 3;</code>
     * @param value The format to set.
     * @return This builder for chaining.
     */
    public Builder setFormat(
        String value) {
      copyOnWrite();
      instance.setFormat(value);
      return this;
    }
    /**
     * <code>string format = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormat() {
      copyOnWrite();
      instance.clearFormat();
      return this;
    }
    /**
     * <code>string format = 3;</code>
     * @param value The bytes for format to set.
     * @return This builder for chaining.
     */
    public Builder setFormatBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFormatBytes(value);
      return this;
    }

    /**
     * <code>string api_version = 4;</code>
     * @return The apiVersion.
     */
    @Override
    public String getApiVersion() {
      return instance.getApiVersion();
    }
    /**
     * <code>string api_version = 4;</code>
     * @return The bytes for apiVersion.
     */
    @Override
    public com.google.protobuf.ByteString
        getApiVersionBytes() {
      return instance.getApiVersionBytes();
    }
    /**
     * <code>string api_version = 4;</code>
     * @param value The apiVersion to set.
     * @return This builder for chaining.
     */
    public Builder setApiVersion(
        String value) {
      copyOnWrite();
      instance.setApiVersion(value);
      return this;
    }
    /**
     * <code>string api_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiVersion() {
      copyOnWrite();
      instance.clearApiVersion();
      return this;
    }
    /**
     * <code>string api_version = 4;</code>
     * @param value The bytes for apiVersion to set.
     * @return This builder for chaining.
     */
    public Builder setApiVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setApiVersionBytes(value);
      return this;
    }

    /**
     * <code>string user_agent = 5;</code>
     * @return The userAgent.
     */
    @Override
    public String getUserAgent() {
      return instance.getUserAgent();
    }
    /**
     * <code>string user_agent = 5;</code>
     * @return The bytes for userAgent.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      return instance.getUserAgentBytes();
    }
    /**
     * <code>string user_agent = 5;</code>
     * @param value The userAgent to set.
     * @return This builder for chaining.
     */
    public Builder setUserAgent(
        String value) {
      copyOnWrite();
      instance.setUserAgent(value);
      return this;
    }
    /**
     * <code>string user_agent = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserAgent() {
      copyOnWrite();
      instance.clearUserAgent();
      return this;
    }
    /**
     * <code>string user_agent = 5;</code>
     * @param value The bytes for userAgent to set.
     * @return This builder for chaining.
     */
    public Builder setUserAgentBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserAgentBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sense.full.v1.Request)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new Request();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "data_",
            "apikey_",
            "format_",
            "apiVersion_",
            "userAgent_",
          };
          String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\n\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<Request> parser = PARSER;
        if (parser == null) {
          synchronized (Request.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<Request>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sense.full.v1.Request)
  private static final Request DEFAULT_INSTANCE;
  static {
    Request defaultInstance = new Request();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Request.class, defaultInstance);
  }

  public static Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Request> PARSER;

  public static com.google.protobuf.Parser<Request> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

